### ISSUE TITLE
Cannot create project

### ISSUE THREAD

**Issue by tilda** [balmjs/balm-cli#5]
Attempting to create a project using `balm init` results in this:
```
C:\Users\NameI\AppData\Roaming\npm\node_modules\balm-cli\lib\check-version.js:21
      const latestVersion = body['dist-tags'].latest;
                                              ^

TypeError: Cannot read property 'latest' of undefined
    at C:\Users\NameI\AppData\Roaming\npm\node_modules\balm-cli\lib\check-version.js:21:47
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

Seems to be coming from the version check that runs every time. I'm using Windows 10 20H2 (insider), Node.js v15.13.0, and npm 7.7.6.

**Comment by elf-mouse** [comment]
Thanks @tilda , I will check and fix it as soon as possible.

**Comment by elf-mouse** [comment]
Hi @tilda , 

You can reinstall and try `2.5.1` now.

Thank you so much again!

**Comment by tilda** [comment]
Works perfectly now, thank you!
